#!/usr/bin/env bash

sudo apt-get update && sudo apt-get install ffmpeg libturbojpeg0 -y

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements.txt --upgrade

mkdir -p config
